// copied from ebiten/keys.go

package ui

import "github.com/hajimehoshi/ebiten"

// A Key represents a keyboard key.
type Key int

// Keys
const (
	Key0         = Key(ebiten.Key0)
	Key1         = Key(ebiten.Key1)
	Key2         = Key(ebiten.Key2)
	Key3         = Key(ebiten.Key3)
	Key4         = Key(ebiten.Key4)
	Key5         = Key(ebiten.Key5)
	Key6         = Key(ebiten.Key6)
	Key7         = Key(ebiten.Key7)
	Key8         = Key(ebiten.Key8)
	Key9         = Key(ebiten.Key9)
	KeyA         = Key(ebiten.KeyA)
	KeyB         = Key(ebiten.KeyB)
	KeyC         = Key(ebiten.KeyC)
	KeyD         = Key(ebiten.KeyD)
	KeyE         = Key(ebiten.KeyE)
	KeyF         = Key(ebiten.KeyF)
	KeyG         = Key(ebiten.KeyG)
	KeyH         = Key(ebiten.KeyH)
	KeyI         = Key(ebiten.KeyI)
	KeyJ         = Key(ebiten.KeyJ)
	KeyK         = Key(ebiten.KeyK)
	KeyL         = Key(ebiten.KeyL)
	KeyM         = Key(ebiten.KeyM)
	KeyN         = Key(ebiten.KeyN)
	KeyO         = Key(ebiten.KeyO)
	KeyP         = Key(ebiten.KeyP)
	KeyQ         = Key(ebiten.KeyQ)
	KeyR         = Key(ebiten.KeyR)
	KeyS         = Key(ebiten.KeyS)
	KeyT         = Key(ebiten.KeyT)
	KeyU         = Key(ebiten.KeyU)
	KeyV         = Key(ebiten.KeyV)
	KeyW         = Key(ebiten.KeyW)
	KeyX         = Key(ebiten.KeyX)
	KeyY         = Key(ebiten.KeyY)
	KeyZ         = Key(ebiten.KeyZ)
	KeyAlt       = Key(ebiten.KeyAlt)
	KeyBackspace = Key(ebiten.KeyBackspace)
	KeyCapsLock  = Key(ebiten.KeyCapsLock)
	KeyComma     = Key(ebiten.KeyComma)
	KeyControl   = Key(ebiten.KeyControl)
	KeyDelete    = Key(ebiten.KeyDelete)
	KeyDown      = Key(ebiten.KeyDown)
	KeyEnd       = Key(ebiten.KeyEnd)
	KeyEnter     = Key(ebiten.KeyEnter)
	KeyEscape    = Key(ebiten.KeyEscape)
	KeyF1        = Key(ebiten.KeyF1)
	KeyF2        = Key(ebiten.KeyF2)
	KeyF3        = Key(ebiten.KeyF3)
	KeyF4        = Key(ebiten.KeyF4)
	KeyF5        = Key(ebiten.KeyF5)
	KeyF6        = Key(ebiten.KeyF6)
	KeyF7        = Key(ebiten.KeyF7)
	KeyF8        = Key(ebiten.KeyF8)
	KeyF9        = Key(ebiten.KeyF9)
	KeyF10       = Key(ebiten.KeyF10)
	KeyF11       = Key(ebiten.KeyF11)
	KeyF12       = Key(ebiten.KeyF12)
	KeyHome      = Key(ebiten.KeyHome)
	KeyInsert    = Key(ebiten.KeyInsert)
	KeyLeft      = Key(ebiten.KeyLeft)
	KeyPageDown  = Key(ebiten.KeyPageDown)
	KeyPageUp    = Key(ebiten.KeyPageUp)
	KeyPeriod    = Key(ebiten.KeyPeriod)
	KeyRight     = Key(ebiten.KeyRight)
	KeyShift     = Key(ebiten.KeyShift)
	KeySpace     = Key(ebiten.KeySpace)
	KeyTab       = Key(ebiten.KeyTab)
	KeyUp        = Key(ebiten.KeyUp)
	KeyMax       = KeyUp
)
